### ISSUE TITLE
karcher dab 7000i internetradio

### ISSUE THREAD

**Issue by marcelrv** [cweiske/frontier-silicon-firmwares#10]
There is the karcher dab 7000i internetradio is has as type/software:
`ir-cui-FS2340-0000-0158_V4.3.6.2402f1-1A5`

(response from)
http://192.168.1.12/fsapi/GET/netRemote.sys.info.version?pin=1234&_=1619780591

**Comment by cweiske** [comment]
This is strange. `FS2340` looks like a new chip (all up to now are `FS2026`), and the `0000` looks like an error.
According to the karcher [press statement](https://www.karcher-products.de/index.php/412/new-digital-radios.html) it's from 2017.

But now I see Venice X at https://frontiersmart.com/sites/default/files/Venice-X_PB.pdf which shows in its footer:
> Venice X FS2340 contains IP licensed from Imagination Technologies Ltd.
