### ISSUE TITLE
Blaupunkt Napoli FW: ir-cui-FS2340-0000-0061_V4.5.6.9526d3-2A2 Advanced Podcasts

### ISSUE THREAD

**Issue by mangrove-art** [cweiske/frontier-silicon-firmwares#23]
Instead of saving singular podcasts in memory saving the emission would be a interesting feature. For example: Instead of saving one dated podcast of news the saved "podcast stream" would propose always the last episodes like on other apps to listen podcasts.

**Comment by cweiske** [comment]
I do not patch firmware, I merely collect existing official ones here.

**Comment by mangrove-art** [comment]
Sorry, firmware research led me to your GitHub page. Thanks for answering.
