### ISSUE TITLE
Teufel Radio 3sixty version

### ISSUE THREAD

**Issue by copitz** [cweiske/frontier-silicon-firmwares#25]
Heyho,

long time no see - hope you are doing fine :)

I just wanted to drop a note, that I think the firmare for Teufel Radio 3sixty listed here is for the 2018 model (without color display). The current one (2020, color display) is `FS2340-0000-0303` according to my sysinfo

Cheers :smile:

**Comment by cweiske** [comment]
Heya :)

Thanks for the info, I've added the radio.

----
The "technical specification says the display resolution is "yes" :-)
![2023-01-02 teufel auflösung ja](https://user-images.githubusercontent.com/59036/210274891-4007c1a1-f8e9-4764-b5b6-66427994f9cf.png)

**Comment by copitz** [comment]
Thanks for the quick reaction :)

Yes, their product infos are not very informative to say the least - it's nearly impossible to find out the versions of their models (I think the "2020" one is this [one here](https://teufel.de/radio-3sixty-2019-105437000) which Teufel says is 2019 but I read somewhere about the first 3sixty being released in 2018)
