### ISSUE TITLE
Do you have any firmware update for the Marshall Woburn MultiRoom?

### ISSUE THREAD

**Issue by gonzabrusco** [cweiske/frontier-silicon-firmwares#26]
The current firmware filename is **ns-mmi-FS5332-0000-0044_1.3.26-41**

**Comment by cweiske** [comment]
At least the URL https://update.wifiradiofrontier.com/sr/FindUpdate.aspx?mac=123&customisation=ns-mmi-FS5332-0000-0044&version=V1.3.26-41 returns a "404 not found", so I guess there is no update.

And it's called "Woburn" not "Woodburn".

**Comment by gonzabrusco** [comment]
Thanks
