### ISSUE TITLE
Two Sonoro Stream devices

### ISSUE THREAD

**Issue by stepo2** [cweiske/frontier-silicon-firmwares#31]
I have two Sonoro Stream devices.

* **ir-mmi-FS2026-0500-0659_V2.11.12c.EX65964-1A1**
* this does **not** have the update tab
* this is the older model

and

* **ir-mmi-FS2026-0500-0789_V2.14.33c.EX85186-1A21**
* this has the update tab for ".sap.bin"
* this is the newer model

The on-device updater on the older device does not update itself to the newer one! This seems to be because Sonoro did not pay Silicon for the 1 or 2 minor extra features for the older devices when the new release came out.

Do you know if it is possible to somehow "cross-flash" similar devices (i.e. updating the older Sonoro Stream to the newer one)? Or will they be bricked afterwards if one tries?

**Comment by cweiske** [comment]
Since we still do not know how to obtain/generate a .sap.bin from a .isu.bin, this is theoretical.

If they have the same hardware chips inside, cross flashing could work. I would not try cross-flashing if different chips are built into the devices.

How is the newer Sonoro Stream device called?
