### ISSUE TITLE
Philips TAM6805/10

### ISSUE THREAD

**Issue by latonita** [cweiske/frontier-silicon-firmwares#36]
Just FYI I have TAM6805/20 for almost a year.
It has following firmware:
`ir-cui-FS2340-0000-0134_V4.5.7.e518da-1A37`

Can't see any updates online though...

current firmware is here https://update.wifiradiofrontier.com/sr/Update.aspx?f=/srupdates/ir-cui-FS2340-0000-0134/ir-cui-FS2340-0000-0134_V4.5.7.e518da-1A37.isu.bin

**Comment by cweiske** [comment]
Thanks! I've added it to the list.

**Comment by cweiske** [comment]
Fixed.
