### ISSUE TITLE
Hama IT900MBT

### ISSUE THREAD

**Issue by breti** [cweiske/frontier-silicon-firmwares#39]
Hi,

my [Hama IT900MBT](https://de.hama.com/webresources/article-documents/00054/man/00054861man_cs_da_de_el_en_es_fi_fr_hu_it_nl_no_pl_pt_ro_ru_sk_sv_tr.pdf) is running Firmware 
ir-mmi-FS2026-0600-0002_V2.12.23.EX70630-1B7

BR,
Jens

**Comment by cweiske** [comment]
Are you sure it's `-0600-`? We only had `0500` and `0200` until now.
And if that one was a typo, please check the other numbers, too.

**Comment by breti** [comment]
Yes, I'm sure!

![grafik](https://github.com/cweiske/frontier-silicon-firmwares/assets/3628895/1eb5488e-862f-454d-b7ba-830782ede090)

**Comment by cweiske** [comment]
Thanks, added.
