### ISSUE TITLE
Firmware for ir-mmi-FS2026-0500-0517_V2.13.13c.EX70970-1RC15

### ISSUE THREAD

**Issue by pniewiadowski** [cweiske/frontier-silicon-firmwares#4]
Hi there,

thank you for this repo.
Are you able to help me figure out how to edit URL to get update for this model?
`ir-mmi-FS2026-0500-0517_V2.13.13c.EX70970-1RC15
`

This is the model:
`SIRD 14 C3
`

**Comment by MomoFab** [comment]
Hi @pniewiadowski 

You have to replace **_V** for a dot **.**

ir-mmi-FS2026-0500-0517 **_V** 2.13.13c.EX70970-1RC15
ir-mmi-FS2026-0500-0517 **.** 2.13.13c.EX70970-1RC15

Tested it, it´s the URL to the desired file:

http://update.wifiradiofrontier.com/Update.aspx?f=/updates/ir-mmi-FS2026-0500-0517.2.13.13c.EX70970-1RC15.isu.bin

**Comment by pniewiadowski** [comment]
It is downloading some *.aspx file. Even I change extension to *.sap.bin it doesn't work.

**Comment by MomoFab** [comment]
I think filename is

ir-mmi-FS2026-0500-0517_V2.13.13c.EX70970-1RC15.isu.bin

Are You trying to upload firmware into device that already have the version V2.13.13c.EX70970-1RC15 on it?

**Comment by cweiske** [comment]
@pniewiadowski Which radio and manufacturer is your 0517?
