### ISSUE TITLE
New Medion Radio MD89289

### ISSUE THREAD

**Issue by J-o-h-n-M** [cweiske/frontier-silicon-firmwares#40]
Posting this here as I am not sure if the download is a correct firmware version.  I bought this radio: https://www.amazon.nl/-/en/P85333-Internet-Spotify-Headphone-line-out/dp/B0BLNKWNBS

And if I go to the web interface of the radio it shows it is **Medion MD89289**

With the information in this github page I found this url

Firmware download (I think this is a correct URL, it downloads a 4000KB file)
https://update.wifiradiofrontier.com/sr/Update.aspx?f=/srupdates/ir-cui-FS2340-0000-0374/ir-cui-FS2340-0000-0374_V4.8.12.d008f1.EX8_4-1A24.isu.bin

**Comment by cweiske** [comment]
Thanks - added.
