### ISSUE TITLE
Silvercrest SMRS18A1 older version 

### ISSUE THREAD

**Issue by zafzafzaf** [cweiske/frontier-silicon-firmwares#41]
Hi thank you for your effort! 
Just writing to add one id to the list. 
I bought a used SMRS18A1 on ebay, ehich came with the following firmware, its web interface has no update menu with file upload option... 

ir-mmi-FS2026-0500-0261_V2.11.11.EX65598-1RC5
Cheers

**Comment by cweiske** [comment]
Thank you.
