### ISSUE TITLE
Any advantage for Noxon iRadio 300 flashing ir-mmi-FS2026-0200-0143_V2.1.11.EX13068-18.isu.bin ?

### ISSUE THREAD

**Issue by kalenderfamily** [cweiske/frontier-silicon-firmwares#45]
Folks nice to see someone collecting information on these crappy units to keep them alive!

I opened the mentioned bin and only found html code inside. 

Did I do anything wrong?

**Comment by cweiske** [comment]
You probably did not download it correctly from github.

Open
https://github.com/cweiske/frontier-silicon-firmwares/blob/master/FS2026-0200/ir-mmi-FS2026-0200-0143_V2.1.11.EX13068-18.isu.bin
and then click the download button on the right.
