### ISSUE TITLE
cant download FS2026-0500-0596

### ISSUE THREAD

**Issue by MomoFab** [cweiske/frontier-silicon-firmwares#5]
Hi at all,

thanks to Christian I have successfully downloaded firmware

ir-mmi-FS2026-0500-0050_V2.6.20c8.EX63098-1A16.isu.bin for Medion MD86988 and
ir-mmi-FS2026-0500-0277_V2.11.13c.EX68399-1RC10.isu.bin for Medion MD87295

but wont work for **ir-mmi-FS2026-0500-0596_V2.9.10c.EX63922-1A2** for Medion MD87559

I tried URL:
http://update.wifiradiofrontier.com/Update.aspx?f=/updates/ir-mmi-FS2026-0500-0596.2.9.10c.EX63922-1A2.isu.bin

Nothing happens, no error...

**Comment by cweiske** [comment]
Seems to be a bug there. It's returning a HTTP status code 200 OK, but the response is empty.
