### ISSUE TITLE
Add link to FSAPI implementation

### ISSUE THREAD

**Issue by stepo2** [cweiske/frontier-silicon-firmwares#50]
Over at https://github.com/flammy/fsapi there is an (unfinished) PHP implementation of the FSAPI with a lot of reverse engineering. This can be used to retrieve (and SET) values on the Silicon Frontier devices.

For example `curl http://<ip-of-device>/fsapi/GET/netRemote.sys.info.version?pin=1234` returns an XML response with the version. There are even endpoints regarding the firmware update.

A link or even information sharing between the two projects will help a lot of people I believe,

**Comment by cweiske** [comment]
The FSAPI documentation is the important thing in that repository. https://github.com/flammy/fsapi/blob/master/FSAPI.md

**Comment by cweiske** [comment]
I've added the link to the api docs.
