### ISSUE TITLE
Firmware file for 2020 Sonoro Stream

### ISSUE THREAD

**Issue by stepo2** [cweiske/frontier-silicon-firmwares#51]
FW file for "Sonoro Stream S0-410 [2020]" (FS2026-0500-0789) can be found there:

https://update.wifiradiofrontier.com/Update.aspx?f=/updates/ir-mmi-FS2026-0500-0789.2.14.33c.EX85186-1A21.isu.bin

**Comment by cweiske** [comment]
Thanks, added.
