### ISSUE TITLE
John Lewis Cello

### ISSUE THREAD

**Issue by POLARIS183** [cweiske/frontier-silicon-firmwares#52]
Hi,

I recently got a John Lewis Cello with firmware number `ir-cui-FS2340-0000-0358.4.8.5.00f64d-1A7`. Please could you add this to your database, so I can get a link to its binary?

Thanks!

**Comment by cweiske** [comment]
I've added the radio, version and firmware file to the repository. You can download it with the "raw" button.

**Comment by POLARIS183** [comment]
Thanks for this!
Sorry if this is a dumb question, but is there a difference between isu.bin and sap.bin files? My Frontier web interface says it can only sideload sap.bin files...

**Comment by cweiske** [comment]
This is a question answered in the readme.
