### ISSUE TITLE
Pinell 101

### ISSUE THREAD

**Issue by blackie333** [cweiske/frontier-silicon-firmwares#53]
Hello, thanks for your project.
have a radio(OKTIV compatible) device model: "Pinell 101"
It was updated to firmware version: ir-cui-FS2340-0000-0176_V4.5.6.9526d3-1A11
It supports manual update from SoftAP update file (.sap.bin) via the local webpage on port 80.

Is there a chance to flash some compatible firmware in case the manufacturer stops providing updates?

**Comment by cweiske** [comment]
I have no idea if a firmware for radio A can be installed on radio B. I'm already happy that we partially know how to manually flash the right firmware files :)

**Comment by blackie333** [comment]
OK, have read somewhere it's not recommended, firmware is always customized for the specific device.
Today my Pinell 101 received another firmware update: ir-cui-FS2340-0000-0176_V4.5.21.d1eb49-1A12

**Comment by cweiske** [comment]
Thanks, added.
