### ISSUE TITLE
FW for Digitradio 600

### ISSUE THREAD

**Issue by pyznarm** [cweiske/frontier-silicon-firmwares#54]
http://update.wifiradiofrontier.com/Update.aspx?f=/updates/ir-mmi-FS2026-0500-0309.2.11.12.EX65933-1RC12.isu.bin

**Comment by cweiske** [comment]
Thanks, added with commit https://github.com/cweiske/frontier-silicon-firmwares/commit/8c7aee4b595c8d5ce906d3bc1974131aeabf3847
