### ISSUE TITLE
FW Digitradio 630

### ISSUE THREAD

**Issue by pyznarm** [cweiske/frontier-silicon-firmwares#55]
Digitradio 630 have FW ir-mmi-FS2026-0500-0772_V2.11.12.EX65933-1A2 , but compile url gave me an error
http://update.wifiradiofrontier.com/Update.aspx?f=/updates/ir-mmi-FS2026-0500-0772.2.11.12.EX65933-1A2.isu.bin

![2024-04-02_18-46-16-1](https://github.com/cweiske/frontier-silicon-firmwares/assets/165833529/322e593a-5293-45ce-89b6-809b7ade3048)

**Comment by cweiske** [comment]
There is no update available when the URL returns a 404.
