### ISSUE TITLE
Blaupunkt PMR 100

### ISSUE THREAD

**Issue by h4de5** [cweiske/frontier-silicon-firmwares#60]
Started initialy with an older firmware that had a lot more options to configure in it's web interface, but it updated automatically once it had access to the internet.

![Screenshot_20241021-054729~2](https://github.com/user-attachments/assets/ec8138ea-fc51-4de6-8be9-e7a250311e04)

ns-mmi-FS5332-0000-0060_1.7.8-16

**Comment by h4de5** [comment]
![PMR_100_gallery2__B075THKFMW MAIN_](https://github.com/user-attachments/assets/77c0a7d0-f488-432e-aed4-6fe8ea6d987f)

**Comment by cweiske** [comment]
Thank you!
