### ISSUE TITLE
Update for Auna iTuner CD

### ISSUE THREAD

**Issue by syma753dfx** [cweiske/frontier-silicon-firmwares#63]
Hi friend,
I have an Auna iTurner CD with PC Wizard, it has on board the following firmware "ir-cui-FS2340-0000-0293_V4.6.10.af681c-1A18", now I would to know if among the firmwares that are published on the github page regarding the frontier silicon chip there is an update suitable for my device, there are many so I don't know which is right, considering that I have the wizzard pc. If you explain to me how to do it I can also download the radio dump and then publish it on the page, it could be useful to someone.
Thanks

**Comment by cweiske** [comment]
I have no information if which firmwares from other devices are suitable for your iTuner.
You'd have to try it out.
The firmware is tailored for the device, so you'd have to find another device that has the same features (inputs and outputs, buttons) as your radio.
