### ISSUE TITLE
trying for medion device ...

### ISSUE THREAD

**Issue by Eddie-BS** [cweiske/frontier-silicon-firmwares#8]
I issued https://update.wifiradiofrontier.com/FindUpdate.aspx?mac=3058906146E8&customisation=ir-mmi-FS2026-0500-0375&version=2.11.12.EX65933-1RC1 in my browser and got the following result 
````
<?xml version="1.0" encoding="UTF-8" ?>
<updates>
  <software customisation="ir-mmi-FS2026-0500-0375"
            version="2.11.12.EX65933-1RC10">
    <copyright>Copyright 2017 Frontier Silicon Ltd</copyright>
    <download>http://update.wifiradiofrontier.com/Update.aspx?c=ir-mmi-FS2026-0500-0375&amp;m=3058906146E8&amp;v=2.11.12.EX65933-1RC1&amp;t=Cust-File&amp;n=2.11.12.EX65933-1RC10&amp;f=/updates/ir-mmi-FS2026-0500-0375.2.11.12.EX65933-1RC10.isu.bin</download>
    <mandatory>false</mandatory>
    <md5>9be297488b6acdac155a3c9e4738c75c</md5>
    <product>Internet Radio</product>
    <size>2409677</size>
    <summary>MP Candidate</summary>
    <vendor>Frontier Silicon</vendor>
  </software>
</updates>
````

when I try to fetch that file in my browser with 
http://update.wifiradiofrontier.com/Update.aspx?f=/updates/ir-mmi-FS2026-0500-0375.2.11.12.EX65933-1RC10.isu.bin
I get this Update.aspx file ...

I guess I did something wrong ?

**Comment by cweiske** [comment]
No, this is alright. You have to rename the file to `ir-mmi-FS2026-0500-0375.2.11.12.EX65933-1RC10.isu.bin`

**Comment by Eddie-BS** [comment]
tnx for the fast response ...
my device says the file needs to be a *.sap.bin file and not a *.isu.bin ...
