### ISSUE TITLE
Add radio(s) and firmware version(s)

### ISSUE THREAD

**Issue by bersbersbers** [cweiske/frontier-silicon-firmwares#9]
There definitely is `ir-mmi-FS2026-0500-0549_V2.12.25c.EX72088-1A12`.

Maybe you can combine that with this information, see also https://community.medion.com/t5/FAQs/Fehlermeldung-Kann-ausgew%C3%A4hltes-Medium-nicht-%C3%B6ffnen/ta-p/99376:

> MD 87990 FS2026-0500-0577 | 1B5
MD 87805 FS2026-0500-0549 | 1A12
MD 87805 FS2026-0500-0710 | 1A3
MD 87505 V2 FS2026-0500-0477 | 1A17
MD 87295 FS2026-0500-0601 | 1A8

**Comment by cweiske** [comment]
I could not download the firmware files.
